# SPDX-License-Identifier: CC0-1.0

name: Release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Check if prerelase
        run: |
          if [[ ${{ github.ref_name }} =~ -(alpha|beta|rc|test) ]]
          then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi
      - name: Install dependencies
        run: sudo apt-get install -y gcc-mingw-w64-x86-64
      - name: Cargo plugins
        run: cargo install --locked cargo-about --features=cli
      - name: Generate licenses
        run: python3 repo-tools/generate_licenses.py
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-gnu && rustup target add
          x86_64-pc-windows-gnu
      - name: Build Linux
        run: cargo build --verbose --release --target=x86_64-unknown-linux-gnu
      - name: Build Windows
        run: cargo build --verbose --release --target=x86_64-pc-windows-gnu
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          artifacts: "target/x86_64-unknown-linux-gnu/release/v_packer,target/x86_64-pc-windows-gnu/release/v_packer.exe,target/x86_64-unknown-linux-gnu/release/v_modelview,target/x86_64-pc-windows-gnu/release/v_modelview.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.PRERELEASE }}
          body: "Release contains binaries for Linux and Windows."
          generateReleaseNotes: true
          artifactErrorsFailBuild: true